#!/bin/bash

WALLPAPER=patience
CODENAME_SAFE=patience
DISPLAY_NAME=Patience
VERSION=2018.2.0
DISTRIBUTION=unstable


# sddm.conf
RELOGIN=false
AUTOSESSION=
AUTOUSER=
NUMLOCK=none
CURSORTHEME=
CURRENTTHEME=debian-theme
REMEMBERLASTSESSION=true
REMEMBERLASTUSER=true

# Main.qml
BOXWIDTH=565
BOXHEIGTH=165
BOXTOPMARGIN=150
BOXCOLOR="#303030"
BOXOPACITY=0.8
BOXRADIUS=12

# metadata.desktop
PREVIEW="images/preview.jpg"

#theme.conf
BACKGROUND="/usr/share/wallpapers/patience/contents/images/1920x1200.jpg"
