#!/bin/bash

WALLPAPER=paintitblack
CODENAME_SAFE=paintitblack
DISPLAY_NAME='PaintItBlack'
VERSION=2015.1.0
DISTRIBUTION=unstable


# sddm.conf
RELOGIN=yes
AUTOSESSION=
AUTOUSER=
NUMLOCK=on
CURSORTHEME=adwaita
REMEMBERLASTSESSION=no
REMEMBERLASTUSER=no

# Main.qml
BOXWIDTH=565
BOXHEIGTH=165
BOXTOPMARGIN=150
BOXCOLOR="#303030"
BOXOPACITY=0.8
BOXRADIUS=12

# metadata.desktop
PREVIEW="images/preview.jpg"

#theme.conf
BACKGROUND="/usr/share/wallpapers/paintitblack/contents/images/1920x1200.jpg"
