#!/bin/bash
 
WALLPAPER=thunderstruck
CODENAME_SAFE=thunderstruck
DESCRIPTION='Thunderstruck'
VERSION=2015.1.0
DISTRIBUTION=unstable


# sddm.conf
RELOGIN=yes
AUTOSESSION=
AUTOUSER=
NUMLOCK=on
THEMENAME=thunderstruck
CURSORTHEME=adwaita
REMEMBERLASTSESSION=no
REMEMBERLASTUSER=no

# Main.qml
BOXCOLOR=green
BOXTOPMARGIN=400

# metadata.desktop
SCREENSHOT=preview

#theme.conf
BACKGROUND=background.jpg
